apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwater
  labels:
    app: underwater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: underwater
  template:
    metadata:
      labels:
        app: underwater
    spec:
      containers:
        - name: underwater
          image: 718511862771.dkr.ecr.us-east-1.amazonaws.com/underwater:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
